version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DEBUG_USER=${DEBUG_USER}
  redis:
    image: "redis:6.0.7"
    command: "redis-server --appendonly yes"
    volumes:
      - ./redis-data:/data
